services:
  app:
    image: ghcr.io/${GITHUB_USER}/blacklotuscms:latest
    container_name: blacklotus-green-app
    ports:
      - "3002:3000"
    volumes:
      - /opt/apps/shared/uploads:/app/uploads
      - blacklotus_green_themes:/app/themes
      - /opt/apps/shared/plugins:/app/plugins
      - ./.env:/app/.env
    env_file:
      - .env
    networks:
      - blacklotus-network
    restart: unless-stopped

volumes:
  blacklotus_green_themes:

networks:
  blacklotus-network:
    external: true
