services:
  app:
    image: ghcr.io/${GITHUB_USER}/blacklotuscms:latest
    container_name: blacklotus-blue-app
    ports:
      - "3001:3000"
    volumes:
      - /home/deploy/portfolio/uploads:/app/uploads
      - ./.env:/app/.env
    env_file:
      - .env
    networks:
      - blacklotus-network
    restart: unless-stopped

networks:
  blacklotus-network:
    external: true
